Fix build with -flto
With CFLAGS="-lflto" the tests fail to build because main() is
redeclared with a different type:

../src/main.c:651:1: error: type of ‘main’ does not match original declaration [-Werror=lto-type-mismatch]
  651 | main(int argc, char **argv)
      | ^
test1.c:47:1: note: type mismatch in parameter 1
   47 | main(void)
      | ^
test1.c:47:1: note: type ‘void’ should match type ‘int’
test1.c:47:1: note: ‘main’ was previously declared here

Simply change the definitions of main() in the tests to match
the one in src/main.c.